### ISSUE TITLE
User Verification Issues

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#202] opened 2022-03-21 16:41 UTC
Experienced two issues with user verification. 

First, when I selected the verification modal in the top menu ribbon, it took me to the view with messaging indicating that no verification info was found (which implies that something is wrong), and to use the verification link sent to my email. I'll note that this user account is an alias of an email with an existing user account, so that could have played a factor. There was no verification link sent to this point. So I selected "resend verification code". A code was sent, which I input. Received the green "verification finalized" message, and then was directed to the screen saying "sorry, there was a problem loading the page".  I logged out, and logged back in and looks like the user account has been successfully verified. 

<img width="705" alt="Screen Shot 2022-03-21 at 10 32 58 AM" src="https://user-images.githubusercontent.com/67928291/159310928-2008bc1e-e7b9-48b3-b459-5793b2bf1c1c.png">
<img width="667" alt="Screen Shot 2022-03-21 at 10 34 08 AM" src="https://user-images.githubusercontent.com/67928291/159310933-e96bd6a5-14ef-403b-b60e-09d151388596.png">

**Comment by wmerfalen** [comment] 2022-04-07 19:44
Haven't found anything obvious. Going to try to reproduce this on staging atleast

**Comment by wmerfalen** [comment] 2022-04-07 20:56
> it took me to the view with messaging indicating that no verification info was found 
From looking at the code, this means that the last verification code sent to your email has expired. So it sat there in the inbox for more than 24 hours

**Comment by wmerfalen** [comment] 2022-04-19 18:43
I'm going to close this for now. We haven't had any issues since the initial incident. We'll keep our eyes peeled for anything similar to this moving forward.

**Closed by wmerfalen** 2022-04-19 18:43 UTC
Labels: bug
