### ISSUE TITLE
Project Statuses [Flows v1.2]

### ISSUE THREAD

**Issue by ddbaker1121** [savvi-legal/feedback#177] opened 2022-03-01 22:12 UTC
Can we have a column in the database on the Project table that says if the workflow is:
1. Not started
2. Open
3. Closed

## Notes

- Problem: I have to find a task on this workflow in order to get to the workflow
  - Solution: Be able to view outstanding instances of an item from the workflow library (the parent 
- Problem: In the Workflow Library, the workflows are marked as "Started" or "Repeatable", but not "Completed"
  - Solution: If all of the tasks within this workflow have been completed, the workflow should be marked as completed.
- Problem: Derek is doing reporting from Stripe, Hubspot, and our DB so we can do a better job of responding to customer behavior
  - Solution: Enable Derek to build Playbooks (IFTTT) around user behavior in the app.

Re: https://trello.com/c/5wFIVP5f/2069-flows-v11

**Comment by BrackCarmony** [comment] 2022-03-18 17:27
Would it make sense to have 1 more state condition of Processing. Where there are no open questionnaires, but not all the tasks have been completed yet. 
Example:  
  All the questionnaires have been submitted to onboard an employee, but there is a document awaiting signatures.
  
1. Not Started:  No questionnaires submitted for project
2. Open: Has at least 1 unsubmitted questionnaire
3. Processing: Has no unsubmitted questionnaires but not all complete tasks. 
4. Closed: All tasks have been submitted.

**Comment by coolaj86** [comment] 2022-03-18 18:35
@ddbaker1121 ^^

**Comment by ddbaker1121** [comment] 2022-03-18 20:12
@BrackCarmony I think that sounds good. Thanks!

**Comment by SHRoberts91** [comment] 2022-03-29 20:39
Duplicate of #190

**Comment by SHRoberts91** [comment] 2022-03-29 20:52
@BrackCarmony Would you be able to look into a solution for the second problem listed here:

> Problem: In the Workflow Library, the workflows are marked as "Started" or "Repeatable", but not "Completed"
Solution: If all of the tasks within this workflow have been completed, the workflow should be marked as completed

Do you think updating the current `status` property/ adding a new property to any of the one-off workflows to mirror the status of their account project? For e.g. in the 'Workflows' view when we call `GET /api/project_template`, the 'Entity Setup` workflow could have the status 'not_started', 'open', closed', etc.

Or maybe we can just add the `status` property to the array of `projects` we're getting back underneath every project template, that's easy enough for me to check too. Or maybe it's not that simple, heh

**Comment by BrackCarmony** [comment] 2022-03-29 21:38
I didn't realize it was being masked in the route.  It's a one string fix.

**Comment by coolaj86** [comment] 2022-03-29 22:23
@BrackCarmony this has been rebased, correct? I'm closing. Please re-open if I'm wrong.

**Closed by coolaj86** 2022-03-29 22:23 UTC
Labels: enhancement
