### ISSUE TITLE
Document information is removed when a document is signed

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#194] opened 2022-03-11 21:35 UTC
![image](https://user-images.githubusercontent.com/68620849/157973454-72ffe2e2-7618-478e-95fb-b386ec09b247.png)

Used to show

![image](https://user-images.githubusercontent.com/68620849/157973635-6416fe30-d52a-4a30-a526-c13b2d293933.png)

**Comment by SHRoberts91** [comment] 2022-03-14 19:44
Pushed a fix and had dan check on live, should be good now.

**Comment by danielandelin** [comment] 2022-03-29 23:01
Still seeing this - 

![image](https://user-images.githubusercontent.com/68620849/160720437-67991f78-2e49-4ee8-9f68-3f3ed5a82ede.png)

**Comment by SHRoberts91** [comment] 2022-04-07 19:38
https://github.com/savvi-legal/app/pull/400 will clean up the ui/language when the document, for whatever reason, gets disconnected from the task. 
It doesn't fix the underlying issue, which is when we try to get documents for that transaction the payload is empty, even though it looks like it has the connected transaction id in the `document_history` table. @BrackCarmony can you look into it when you have time and see if you have any idea what's up? It seems to sometimes work and sometimes doesn't, and has been happening for a while.

Steps to reproduce live issue:
1. Possess "Localshift.io, Inc."
2. Go to the [Plan of Conversion](https://app.savvi.legal/c/1943824127/workbench/tasks/11320/24609/task-view) task. (the 'Conversion Documents' Task in the image above is no longer a good test because they deleted the documents)
3. The payload for that transaction documents(`GET /api/account/transaction/24609/documents`) is empty. Even though the document has the `account_task_id`, `account_transaction_id` & `account_project_id` (search the `document_history` table by `box_file_id` of `935673759411`.

**Closed** 2022-04-29 21:35 UTC
